function fvcbParams = getFvCBParams
fvcbParams = struct(...
    'k_c',config('k_c'),...
    'k_o',config('k_o'),...
    'K_c',config('K_c'),...
    'K_o',config('K_o'),...
    'E_a',config('E_a'),...
    'J_max',config('J_max'),...
    'V_c_max',config('V_c_max'));
end